/**
 * End-to-end tests: MHTML file → full pipeline → CSV output.
 *
 * The expected CSV files in test/fixtures/ were generated by running this test
 * suite for the first time with GENERATE_FIXTURES=1, which writes the actual
 * pipeline output as the golden reference files.
 *
 * Usage:
 *   Normal run:    npm test               (compares against fixtures)
 *   Regenerate:    GENERATE_FIXTURES=1 npx vitest run test/e2e.test.ts
 */
import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { parseMhtmlFromMorganStanley } from '../src/parser';
import { parseExchangeRates, processTransactions } from '../src/calculator';
import { generateFullCsv, generateTaxCsv } from '../src/csv_generator';

const FIXTURES_DIR = path.join(__dirname, 'fixtures');
const EXCHANGE_RATES_CSV = path.join(__dirname, '../src/won_dollar_exchange_rate.csv');
const GENERATE = process.env.GENERATE_FIXTURES === '1';

function runPipeline(mhtmlBasename: string) {
  const ratesCsv = fs.readFileSync(EXCHANGE_RATES_CSV, 'utf-8');
  const rates = parseExchangeRates(ratesCsv);

  const mhtmlContent = fs.readFileSync(
    path.join(FIXTURES_DIR, `${mhtmlBasename}.mhtml`),
    'utf-8'
  );
  const parsed = parseMhtmlFromMorganStanley(mhtmlContent, `${mhtmlBasename}.mhtml`);
  const processed = processTransactions([parsed], rates);

  return {
    fullCsv: generateFullCsv(processed),
    taxCsv: generateTaxCsv(processed),
  };
}

function checkOrWrite(fixturePath: string, actual: string) {
  if (GENERATE) {
    fs.writeFileSync(fixturePath, actual, 'utf-8');
  } else {
    const expected = fs.readFileSync(fixturePath, 'utf-8');
    expect(actual).toBe(expected);
  }
}

describe('E2E: test-ms-one-record', () => {
  it('produces correct full verification CSV', () => {
    const { fullCsv } = runPipeline('test-ms-one-record');
    checkOrWrite(path.join(FIXTURES_DIR, 'test-ms-one-record-full.csv'), fullCsv);
  });

  it('produces correct Korean tax filing CSV', () => {
    const { taxCsv } = runPipeline('test-ms-one-record');
    checkOrWrite(path.join(FIXTURES_DIR, 'test-ms-one-record-tax.csv'), taxCsv);
  });
});

describe('E2E: test-ms-four-records', () => {
  it('produces correct full verification CSV', () => {
    const { fullCsv } = runPipeline('test-ms-four-records');
    checkOrWrite(path.join(FIXTURES_DIR, 'test-ms-four-records-full.csv'), fullCsv);
  });

  it('produces correct Korean tax filing CSV', () => {
    const { taxCsv } = runPipeline('test-ms-four-records');
    checkOrWrite(path.join(FIXTURES_DIR, 'test-ms-four-records-tax.csv'), taxCsv);
  });
});
